@host = http://localhost:8080
@contentType = application/json

### GET all doctors(starts from 1 page)
GET {{host}}/api/doctors?page=1&size=10

### GET doctor by ID
@id = 13c70af8-7676-45df-a2ec-252a03424849
GET {{host}}/api/doctors/{{id}}

### POST new doctor (Original)
POST {{host}}/api/doctors
Content-Type: {{contentType}}

{
  "firstName": "Joe",
  "lastName": "Doe",
  "address": "13 Clueless Area, Springfield",
  "email": "joedoe@example.com",
  "experience": "Junior"
}

### POST new doctor (Test Case 1)
POST {{host}}/api/doctors
Content-Type: {{contentType}}

{
  "firstName": "Amara",
  "lastName": "Patel",
  "address": "245 Oakwood Lane, Boston, MA 02108",
  "email": "amara.patel@healthcare.org",
  "specialization": "Cardiology",
  "experience": "Senior"
}

### POST new doctor (Test Case 2)
POST {{host}}/api/doctors
Content-Type: {{contentType}}

{
  "firstName": "Liam",
  "lastName": "O'Connor",
  "address": "789 Pine Street, Seattle, WA 98101",
  "email": "liam.oconnor@medmail.com",
  "specialization": "Ophthalmology",
  "experience": "Expert"
}

### POST new doctor (Test Case 3)
POST {{host}}/api/doctors
Content-Type: {{contentType}}

{
  "firstName": "Sofia",
  "lastName": "Mendez",
  "email": "sofia.mendez@clinic.net",
  "specialization": "Emergency",
  "experience": "Junior"
}

### PATCH doctor
PATCH {{host}}/api/doctors/{{id}}
Content-Type: {{contentType}}

{
  "firstName": "William",
  "email": "william.hello@example.com"
}

### PUT doctor
PUT {{host}}/api/doctors/{{id}}
Content-Type: {{contentType}}

{
  "firstName": "Michael",
  "lastName": "Smith",
  "address": "30 Joe Doe Street, Chicago, IL 60601",
  "email": "michael.smith@example.com",
  "specialization": "Oncologists",
  "experience": "Senior"
}

### DELETE doctor
DELETE {{host}}/api/doctors/{{id}}