@host = http://localhost:8080
@contentType = application/json

### GET all insurances(starts from 1 page)
GET {{host}}/api/insurances?page=1&size=10

### GET insurance by ID 
@id = 21fd58b9-6873-4f12-b4c0-877cb5e78ec1
GET {{host}}/api/insurances/{{id}}

### POST new insurance (Original)
POST {{host}}/api/insurances
Content-Type: {{contentType}}

{
  "companyName": "Nescol Insurance",
  "address": "28 Nescol Street, Aberdeen, AB10 1YL",
  "phoneNumber": "0123456789"
}

### POST new insurance (Test Case 1)
POST {{host}}/api/insurances
Content-Type: {{contentType}}

{
  "companyName": "BlueCross Health",
  "address": "123 Wellness Avenue, Boston, MA 02110",
  "phoneNumber": "617-555-1234"
}

### POST new insurance (Test Case 2)
POST {{host}}/api/insurances
Content-Type: {{contentType}}

{
  "companyName": "Aetna Insurance",
  "address": "456 Harmony Road, Chicago, IL 60601",
  "phoneNumber": "3125555678"
}

### POST new insurance (Test Case 3)
POST {{host}}/api/insurances
Content-Type: {{contentType}}

{
  "companyName": "Cigna Global",
  "phoneNumber": "+415-555-9012"
}

### PATCH insurance
PATCH {{host}}/api/insurances/{{id}}
Content-Type: {{contentType}}

{
  "companyName": "RGU Insurance"
}

### PUT insurance
PUT {{host}}/api/insurances/{{id}}
Content-Type: {{contentType}}

{
  "companyName": "RGU Insurance",
  "address": "28 RGU Street, Aberdeen, AB11 5YU",
  "phoneNumber": "024-135-7698"
}

### DELETE insurance
DELETE {{host}}/api/insurances/{{id}}