@host = http://localhost:8080
@contentType = application/json

### GET all visits
GET {{host}}/api/visits?page=1&size=10

### GET visit by composite ID
@doctorId = 13c70af8-7676-45df-a2ec-252a03424849
@patientId = 3f2ae8df-b178-44c1-a086-425a6efce818
@visitDate = 2025-06-11
GET {{host}}/api/visits/{{patientId}}/{{doctorId}}/{{visitDate}}

### POST new visit (Original, Updated)
POST {{host}}/api/visits
Content-Type: {{contentType}}

{
  "id": {
    "patientId": "{{patientId}}",
    "doctorId": "{{doctorId}}",
    "visitDate": "{{visitDate}}"
  },
  "symptoms": "Fever, cough, fatigue",
  "diagnosis": 4870
}

### POST new visit (Test Case 1)
POST {{host}}/api/visits
Content-Type: {{contentType}}

{
  "id": {
    "patientId": "{{patientId}}",
    "doctorId": "{{doctorId}}",
    "visitDate": "{{visitDate}}"
  },
  "symptoms": "Chest pain, shortness of breath",
  "diagnosis": 4139
}

### POST new visit (Test Case 2)
POST {{host}}/api/visits
Content-Type: {{contentType}}

{
  "id": {
    "patientId": "{{patientId}}",
    "doctorId": "{{doctorId}}",
    "visitDate": "{{visitDate}}"
  },
  "symptoms": "Abdominal pain, nausea",
  "diagnosis": 53550
}

### POST new visit (Test Case 3)
POST {{host}}/api/visits
Content-Type: {{contentType}}

{
  "id": {
    "patientId": "{{patientId}}",
    "doctorId": "{{doctorId}}",
    "visitDate": "{{visitDate}}"
  },
  "symptoms": "Joint pain, swelling",
  "diagnosis": 7140
}

### PATCH visit
PATCH {{host}}/api/visits/{{patientId}}/{{doctorId}}/{{visitDate}}
Content-Type: {{contentType}}

{
  "symptoms": "Fever, sore throat, cough",
  "diagnosis": 4659
}

### PUT visit
PUT {{host}}/api/visits/{{patientId}}/{{doctorId}}/{{visitDate}}
Content-Type: {{contentType}}

{
  "symptoms": "Headache, nasal congestion",
  "diagnosis": 460
}

### DELETE visit
DELETE {{host}}/api/visits/{{patientId}}/{{doctorId}}/{{visitDate}}